# -*- coding: utf-8 -*-
"""컴퓨터과학과 202510778 권해진

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGo4uIDrt8APBRabkchiJapGCQyUnEf7
"""

prompt="넓이를 구하고자 하는 원의 반지름은?"
def get_radius(prompt):
  r=int(input(prompt))
  return r
def get_circle_area():
  r=get_radius(prompt)
  s=3.14*r*r
  print("반지름",r,"인 원의 넓이",s)
  return s
print("시작")
result=get_circle_area()
print("끝")
input()