# -*- coding: utf-8 -*-
"""hw2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQeK81qje3_ei0DC83NJxuy9WraUo7bk
"""

def exchange(n):
  a=n//500
  b=(n%500)//100
  c=(n%100)//50
  d=(n%50)//10
  print("500원 동전의 개수:",a)
  print("100원 동전의 개수:",b)
  print("50원 동전의 개수:",c)
  print("10원 동전의 개수:",d)

def get_integer(prompt):
  n=int(input(prompt))
  return n

print("시작")
result=get_integer("동전으로 교환하고자 하는 금액은?")
exchange(result)
print("끝")
input()